server:
  port: 3333

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: PLATFORM-DEMO
          uri: lb://Platform-Demo  # Load balanced URI to Platform-Demo service
          predicates:
            - Path=/test/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# Eureka client configuration for service discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

msg: Hello from API Gateway!