server:
  port: 3333

spring:
  application:
    name: Api-Gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

      
msg: Api-Gateway is called from github...