server:
  port: 3333

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: platform-demo
          uri: lb://Platform-Demo  # Load balanced URI to Platform-Demo service
          predicates:
            - Path=/test


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

      
msg: Api-Gateway is called from github...