spring:
  config:
    import: optional:configserver:http://localhost:8080
  application:
    name: Api-Gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: greet-api
          uri: lb:GREET-API
          predicates:
            - Path=/greet/**

server:
  port: 3333