server:
  port: 9090

spring:
  application:
    name: Platform-Demo

# Eureka client configuration  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

msg: Hello from Platform Demo!
